BarSi/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BarSi.Data;
using BarSi.Models;
using Microsoft.AspNetCore.Http;

namespace BarSi.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly BarSiContext _context;

        public DoctorsController(BarSiContext context)
        {
            _context = context; 
        }

        // GET: Doctors
        public async Task<IActionResult> Index()
        {
            ViewData["IsAdmin"] = IsAdmin();
            return View(await _context.Doctor.Include(d => d.City).Include(d => d.Hospital).ToListAsync());
        }

        public async Task<IActionResult> Search(string first_name, string last_name, string city, string hospital)
        {
            var doctors = _context.Doctor.AsQueryable();
            if (!String.IsNullOrEmpty(first_name))
                doctors = doctors.Where(d => d.FirstName.ToLower().Contains(first_name.ToLower()));
            if (!String.IsNullOrEmpty(last_name))
                doctors = doctors.Where(d => d.LastName.ToLower().Contains(last_name.ToLower()));
            if (!String.IsNullOrEmpty(hospital))
                doctors = doctors.Where(d => d.Hospital.Name.Contains(hospital));
            if (!String.IsNullOrEmpty(city))
                doctors = doctors.Where(d => d.City.Name.Contains(city));


            var doctors_results = await doctors.Include(d => d.City).Include(d => d.Hospital).ToListAsync();
            var doctors_relevent_data = doctors_results.Select(d =>
            new
            {
                Id = d.Id,
                FirstName = d.FirstName,
                LastName = d.LastName,
                Birthdate = d.Birthdate.ToString("dd-MM-yyyy"),
                Hospital = d.Hospital.Name,
                City = d.City.Name,
            }).ToList();

            return Json(doctors_relevent_data);
        }

        // GET: Doctors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            IsAdmin();
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctor.Include(d => d.City).Include(d => d.Hospital)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            if (!IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["Hospitals"] = new SelectList(_context.Hospital, "Id", "Name");
            ViewData["Cities"] = new SelectList(_context.City, "Id", "Name");
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Birthdate")] Doctor doctor, int Hospital, int City)
        {
            if (ModelState.IsValid)
            {
                UpdateComplexDoctorProps(doctor, Hospital, City);
                _context.Add(doctor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctor.Include(d => d.City).Include(d => d.Hospital).FirstAsync(d => d.Id == id);
            if (doctor == null)
            {
                return NotFound();
            }
            ViewData["Hospitals"] = new SelectList(_context.Hospital, "Id", "Name", doctor.Hospital.Id);
            ViewData["Cities"] = new SelectList(_context.City, "Id", "Name", doctor.City.Id);

            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Birthdate")] Doctor doctor, int Hospital, int City)
        {
            if (id != doctor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                UpdateComplexDoctorProps(doctor, Hospital, City);

                try
                {
                    _context.Update(doctor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorExists(doctor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctor.Include(d => d.City).Include(d => d.Hospital)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var doctor = await _context.Doctor.FindAsync(id);
                _context.Doctor.Remove(doctor);
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {
                return Content("Unable to delete");
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Doctors/PatientsForDoctorStatistic
        public IActionResult PatientsForDoctorStatistic()
        {
            var patientsByDoctor = from p in _context.Patient
                                     group p by p.Doctor.Id into g
                                     select new
                                     {
                                         g.Key,
                                         Count = g.Count()
                                     };

            var patientsCountByDoctor = from pd in patientsByDoctor
                                          join d in _context.Doctor
                                          on pd.Key equals d.Id
                                          select new { DoctorName = d.FirstName + " " + d.LastName, PatientsCount = pd.Count };

            //var patientsForDoctorStatistic = from pd in patientsCountByDoctor
            //                                 group pd by pd.PatientsCount into g
            //                                 select new
            //                                 {
            //                                     PatientsCount = g.Key,
            //                                     DoctorsCount = g.Count()
            //                                 }; ;

            return Json(patientsCountByDoctor.ToList());
        }

        private bool DoctorExists(int id)
        {
            return _context.Doctor.Any(e => e.Id == id);
        }

        private void UpdateComplexDoctorProps(Doctor doctor, int hospital, int city)
        {
            doctor.Hospital = _context.Hospital.First(h => h.Id == hospital);
            doctor.City = _context.City.First(c => c.Id == city);
        }

        private bool IsAdmin()
        {
            bool isAdmin = (HttpContext != null) && (HttpContext.Session != null) &&
                                 (HttpContext.Session.GetString("IsAdmin") == "true");
            ViewData["IsAdmin"] = isAdmin;
            return isAdmin;
        }
    }
}

BarSi/Controllers/MedicalEquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BarSi.Data;
using BarSi.Models;
using Microsoft.AspNetCore.Http;

namespace BarSi.Controllers
{
    public class MedicalEquipmentsController : Controller
    {
        private readonly BarSiContext _context;

        public MedicalEquipmentsController(BarSiContext context)
        {
            _context = context;
        }

        // GET: MedicalEquipments
        public async Task<IActionResult> Index()
        {
            ViewData["IsAdmin"] = IsAdmin();
            return View(await _context.MedicalEquipment.ToListAsync());
        }

        // GET: MedicalEquipments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            IsAdmin();
            if (id == null)
            {
                return NotFound();
            }

            var medicalEquipment = await _context.MedicalEquipment
                .Include(m => m.medicalEquipmentSupplies/*.Where(s => s.MedicalEquipmentId == m.Id)*/)
                .ThenInclude(item => item.Hospital)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (medicalEquipment == null)
            {
                return NotFound();
            }

            //ViewBag.Supplies = new SelectList(_context.MedicalEquipmentSupply.ToList(), "HospitalId", "Name", "SupplyQuantity");

            return View(medicalEquipment);
        }

        // GET: MedicalEquipments/Create
        public IActionResult Create()
        {
            if (!IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        // POST: MedicalEquipments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Quantity")] MedicalEquipment medicalEquipment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicalEquipment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medicalEquipment);
        }

        // GET: MedicalEquipments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var medicalEquipment = await _context.MedicalEquipment.FindAsync(id);
            if (medicalEquipment == null)
            {
                return NotFound();
            }
            return View(medicalEquipment);
        }

        // POST: MedicalEquipments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Quantity")] MedicalEquipment medicalEquipment)
        {
            if (id != medicalEquipment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicalEquipment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicalEquipmentExists(medicalEquipment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicalEquipment);
        }

        // GET: MedicalEquipments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!IsAdmin())
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var medicalEquipment = await _context.MedicalEquipment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medicalEquipment == null)
            {
                return NotFound();
            }

            return View(medicalEquipment);
        }

        // POST: MedicalEquipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medicalEquipment = await _context.MedicalEquipment.FindAsync(id);
            _context.MedicalEquipment.Remove(medicalEquipment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicalEquipmentExists(int id)
        {
            return _context.MedicalEquipment.Any(e => e.Id == id);
        }

        private bool IsAdmin()
        {
            bool isAdmin = (HttpContext != null) && (HttpContext.Session != null) &&
                                 (HttpContext.Session.GetString("IsAdmin") == "true");
            ViewData["IsAdmin"] = isAdmin;
            return isAdmin;
        }
    }
}

BarSi/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BarSi.Data;
using BarSi.Models;
using Microsoft.AspNetCore.Http;

namespace BarSi.Controllers
{
    public class UsersController : Controller
    {
        private readonly BarSiContext _context;

        public UsersController(BarSiContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            var user = await _context.User.FirstOrDefaultAsync(m => m.Name == username);

            if (user != null && user.Password == password)
            {
                HttpContext.Session.SetString("IsAdmin", "true");
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout(string username, string password)
        {
            HttpContext.Session.SetString("IsAdmin", "false");
            return RedirectToAction("Index", "Home");
        }

        private bool IsAdmin()
        {
            bool isAdmin = (HttpContext != null) && (HttpContext.Session != null) &&
                                 (HttpContext.Session.GetString("IsAdmin") == "true");
            ViewData["IsAdmin"] = isAdmin;
            return isAdmin;
        }
    }
}

BarSi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarSi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome-free-5.13.1-web/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header id="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow" id="main-nav">
            <div class="container" id="navbar">
                <a class="navbar-brand" id="home-item" asp-area="" asp-controller="Home" asp-action="Index">BarSi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home nav-icon"></i>
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Patients" asp-action="Index">
                                <i class="fas fa-procedures nav-icon"></i>
                                Patients
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Doctors" asp-action="Index">
                                <i class="fas fa-user-md nav-icon"></i>
                                Doctors
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Hospitals" asp-action="Index">
                                <i class="fas fa-clinic-medical nav-icon"></i>
                                Hospitals
                            </a>
                        </li>
                        <li class="nav-item" id="medical-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="MedicalEquipments" asp-action="Index">
                                <i class="fas fa-stethoscope nav-icon"></i>
                                Medical Equipments
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="loginButton">
                    @if (!@ViewBag.IsAdmin)
                    {
                        <button type="button" class="btn btn-outline-light btn-round"
                                data-toggle="modal" data-target="#loginModal">
                            Login
                        </button>
                    }
                    else
                    {
                        <button class="btn btn-outline-light btn-block btn-round"
                                onclick="location.href='@Url.Action("Logout", "Users")'">
                            Logout
                        </button>
                    }
                </div>
                <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <form id="login-form" asp-action="Login" asp-controller="Users" novalidate>
                                <header class="modal-header">
                                    <div class="form-title">
                                        <h4>Login</h4>
                                    </div>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </header>
                                <section class="modal-body">
                                    <div class="d-flex flex-column text-center">
                                        <div class="form-group">
                                            <input type="text" name="username" class="form-control" id="username" placeholder="Your username..." autocomplete="off" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password" class="form-control" id="password" placeholder="Your password..." required>
                                        </div>
                                    </div>
                                </section>
                                <footer class="modal-footer d-flex justify-content-center">
                                    <input type="submit" value="Login" class="btn btn-info btn-block btn-round" />
                                </footer>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid" id="body-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*<div class="container">
                &copy; 2020 - BarSi
            </div>*@
        <canvas id="footer-canvas" width="200" height="25"></canvas>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>